### ISSUE TITLE
Fix packs API

### ISSUE THREAD

**Issue by dfomin** [gregzhadko/hat-server-asp-net-core#8]
1. Add pack version.
2. Add number of pack phrases.
3. Never send empty array of phrases if pack has phrases. Drop that field for packs request, send all phrases for concrete pack request.

**Comment by gregzhadko** [comment]
@dfomin Why do we need the second point?

**Comment by dfomin** [comment]
We show the number of phrases in pack on pack list screen.
4. Add possibility to request all packs with all phrases in one request.

**Comment by gregzhadko** [comment]
It seems that everything was implemented
